import UseTitle from "../../Hoks/useTitle";

const Blog = () => {

    UseTitle('Blog')
    return (
        <div className='w-2/4 mx-auto mt-10 mb-14'>
            <div >
                <h1 className='text-center text-4xl font-bold underline mb-6'> Question & Answer page</h1>
                <div className='shadow-xl'>
                    <div className=' p-10'>
                        <h2 className='text-2xl font-semibold'>1. What is an access token and refresh token? How do they work and where should we store them on the client-side?</h2>
                        <blockquote className='ps-5 mt-4'>
                            <p>Access tokens are typically generated by an authorization server when
                                a user authenticates with a client application. The authorization
                                server will issue an access token to the client application, which can
                                then use the access token to access protected resources. Access tokens
                                are typically valid for a short period of time, such as 30 minutes or
                                an hour. Once an access token expires, the client application will
                                need to obtain a new access token from the authorization server.</p>

                        </blockquote>
                    </div>
                    <div className='p-10'>
                        <h2 className='text-2xl font-semibold'>2. Compare SQL and NoSQL databases?
                        </h2>
                        <blockquote className='ps-5 mt-4'>
                            <p>SQL databases store data in tables, which are made up of rows and
                                columns. Each row represents a single record, and each column
                                represents a single piece of data about that record. SQL databases use
                                a structured query language (SQL) to access and manipulate data. NoSQL
                                databases store data in a variety of ways, including key-value pairs,
                                documents, and graphs. NoSQL databases do not use SQL to access and
                                manipulate data. Instead, they use a variety of different methods,
                                depending on the type of NoSQL database.</p>

                        </blockquote>
                    </div>
                    <div className='p-10'>
                        <h2 className='text-2xl font-semibold'>3. What is express js? What is Nest JS ?</h2>
                        <blockquote className='ps-5 mt-4'>
                            <p>Express.js is a web application framework for Node.js. It is a
                                minimalist framework that provides a set of core features that can be
                                used to build web applications. Express.js is easy to learn and use,
                                and it is highly scalable. Nest.js is a framework for building
                                server-side applications using JavaScript. It is built on top of
                                Express.js, and it provides a number of features that make it easier
                                to build scalable and maintainable applications. Nest.js is a good
                                choice for building applications that require a high degree of
                                scalability and reliability.
                            </p>
                        </blockquote>
                    </div>
                    <div className='p-10'>
                        <h2 className='text-2xl font-semibold'>4. What is MongoDB aggregate and how does it work ?
                        </h2>
                        <blockquote className='ps-5 mt-4'>
                            <p>  MongoDB aggregate is a feature of MongoDB that allows you to perform
                                complex queries on your data. Aggregate queries are used to perform
                                operations such as grouping, sorting, and filtering on your data.
                                Aggregate queries are written using the aggregation pipeline, which is
                                a series of steps that are applied to your data in order to produce
                                the desired results.</p>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Blog;